include_recipe 'recipe_helper'

include_cookbook 'functions'

include_cookbook 'go'
include_cookbook 'git'
include_cookbook 'tmux'
include_cookbook 'nvim'
include_cookbook 'ghq'
include_cookbook 'peco'
include_cookbook 'zsh'
include_cookbook 'wezterm'
include_cookbook 'starship'
include_cookbook 'envchain'
include_cookbook 'jq'
